name: "Build and deploy"
on:
        push:
                branches:
                        - master
jobs:
        build:
                runs-on: ubuntu-latest
steps:
                - name: Fetch master branch
                  uses: actions/checkout@v2
                - name: Grant gradle rights
                  run: chmod +x ./gradlew
                - name: Build Release APK with Gradle
                  run: ./gradlew clean bundleRelease